### ISSUE TITLE
Should the Toolkit support Scala 2.12?

### ISSUE THREAD

**Issue by SethTisue** [scala/toolkit#3]
I can see the temptation to let the answer be "yes", since the libraries that have been selected all work on 2.12.

But I want to at least raise the question that maybe the answer should be "no".

Scala 2.12 isn't EOL, but it's in a semi-EOL state where anything more than the lightest, most minimal maintenance is only happening because of a single commercial sponsor.

I think we could reasonably say, if you want to use the toolkit you should be on 2.13 or 3, we aren't interested in offering this brand-new thing on a half-dead Scala version series.

Even if supporting 2.12 wouldn't cause us any special difficulty _at the moment_, it might cause us trouble and slow us down _down the road_, and since the toolkit is new, now's our chance to just not support 2.12 right from the very start.

**Comment by szymon-rd** [comment]
We will go forward with dropping 2.12. Supporting 2.12 creates additional maintenance costs for us (due to different API), and may lead to confusion for the users (when they would see collections being used differently). With a high probability, in the near future, we would also face some problems with the libraries for 2.12.
